from pathlib import Path

from codecleaner.features.extractor import FeatureExtractor


def test_extracts_noise_features(tmp_path: Path):
    path = tmp_path / "main.py"
    path.write_text(
        "# This function handles the user request.\n"
        "# This function handles the user request.\n"
        "\n"
        "print('hello')\n"
        "print('hello')\n",
        encoding="utf-8",
    )

    features = FeatureExtractor().extract_file(tmp_path, path)

    assert features.total_lines == 5
    assert features.comment_lines == 2
    assert features.blank_lines == 1
    assert features.code_lines == 2
    assert features.comment_repetition > 0
    assert features.duplicate_line_ratio > 0
    assert features.comment_ratio == 0.4
    assert features.blank_line_ratio == 0.2


def test_generated_phrase_signal(tmp_path: Path):
    path = tmp_path / "main.py"
    path.write_text(
        "# Generated by ChatGPT\n"
        "print('hello')\n",
        encoding="utf-8",
    )

    features = FeatureExtractor().extract_file(tmp_path, path)

    assert features.generated_phrase_density == 0.5
    assert features.boilerplate_density == 0.5


def test_project_extraction(tmp_path: Path):
    first = tmp_path / "a.py"
    second = tmp_path / "b.py"
    first.write_text("print('a')\n", encoding="utf-8")
    second.write_text("print('b')\n", encoding="utf-8")

    features = FeatureExtractor().extract_project(
        tmp_path,
        [first, second],
    )

    assert [item.file for item in features] == ["a.py", "b.py"]
