from pathlib import Path

from codecleaner.transformation.diff import generate_file_diff


def test_diff_detects_removed_line(tmp_path: Path):
    original = tmp_path / "original.py"
    cleaned = tmp_path / "cleaned.py"

    original.write_text(
        "# Generated by Claude\n"
        "print('hello')\n",
        encoding="utf-8",
    )

    cleaned.write_text(
        "print('hello')\n",
        encoding="utf-8",
    )

    diff = generate_file_diff(
        original,
        cleaned,
    )

    assert "-# Generated by Claude" in diff
    assert "+print('hello')" not in diff
