from pathlib import Path

from codecleaner.classification.engine import ClassificationEngine
from codecleaner.detection.engine import DetectionEngine
from codecleaner.transformation.engine import TransformationEngine
from codecleaner.transformation.models import TransformStatus


def test_transform_does_not_modify_source(tmp_path: Path):
    source = tmp_path / "source"
    output = tmp_path / "output"

    source.mkdir()

    original = source / "main.py"
    original.write_text(
        "# Generated by Claude\n"
        "\n"
        "def hello():\n"
        "    return 'hello'\n",
        encoding="utf-8",
    )

    detections = DetectionEngine().scan_file(source, original)
    findings = ClassificationEngine().classify_many(detections)

    results = TransformationEngine().transform(
        source,
        output,
        findings,
    )

    assert len(results) == 1
    assert results[0].status == TransformStatus.CHANGED
    assert results[0].removed_lines == 1

    assert "# Generated by Claude" in original.read_text(
        encoding="utf-8"
    )

    cleaned = output / "main.py"

    assert "# Generated by Claude" not in cleaned.read_text(
        encoding="utf-8"
    )

    assert "def hello():" in cleaned.read_text(
        encoding="utf-8"
    )


def test_no_findings_creates_identical_copy(tmp_path: Path):
    source = tmp_path / "source"
    output = tmp_path / "output"

    source.mkdir()

    original = source / "main.py"

    original.write_text(
        "def hello():\n"
        "    return 'hello'\n",
        encoding="utf-8",
    )

    results = TransformationEngine().transform(
        source,
        output,
        [],
    )

    assert results == []

    cleaned = output / "main.py"

    assert cleaned.read_text(
        encoding="utf-8"
    ) == original.read_text(
        encoding="utf-8"
    )


def test_multiple_removable_lines(tmp_path: Path):
    source = tmp_path / "source"
    output = tmp_path / "output"

    source.mkdir()

    original = source / "main.py"

    original.write_text(
        "# Generated by Claude\n"
        "# AI-generated code\n"
        "\n"
        "print('hello')\n",
        encoding="utf-8",
    )

    detections = DetectionEngine().scan_file(source, original)
    findings = ClassificationEngine().classify_many(detections)

    results = TransformationEngine().transform(
        source,
        output,
        findings,
    )

    assert results[0].removed_lines == 2

    cleaned = (output / "main.py").read_text(
        encoding="utf-8"
    )

    assert "Generated by Claude" not in cleaned
    assert "AI-generated code" not in cleaned
    assert "print('hello')" in cleaned
