from pathlib import Path

from codecleaner.core.scanner import scan_project


def test_scanner_detects_ai_attribution(tmp_path: Path):
    source = tmp_path / "main.py"

    source.write_text(
        "# Generated by Claude\n"
        "\n"
        "def hello():\n"
        "    return 'hello'\n",
        encoding="utf-8",
    )

    result = scan_project(tmp_path)

    assert result.files_scanned == 1
    assert len(result.findings) == 1
    assert result.findings[0].category == "ai_attribution"
    assert result.findings[0].confidence >= 0.99


def test_scanner_preserves_license(tmp_path: Path):
    source = tmp_path / "main.py"

    source.write_text(
        "# Copyright 2026 Example\n"
        "# Licensed under the MIT License\n"
        "\n"
        "print('hello')\n",
        encoding="utf-8",
    )

    result = scan_project(tmp_path)

    assert len(result.findings) == 0
