from pathlib import Path
import zipfile

from codecleaner.cli import clean_project


def test_clean_project_end_to_end(tmp_path):
    source = tmp_path / "input"
    output = tmp_path / "output"
    reports = tmp_path / "reports"
    archive = tmp_path / "cleaned.zip"

    source.mkdir()

    original = source / "main.py"
    original.write_text(
        "# Generated by ChatGPT\n"
        'print("hello")\n',
        encoding="utf-8",
    )

    exit_code = clean_project(
        source,
        output,
        reports,
        archive,
    )

    assert exit_code == 0
    assert original.read_text(encoding="utf-8") == (
        "# Generated by ChatGPT\n"
        'print("hello")\n'
    )

    assert (output / "main.py").read_text(encoding="utf-8") == (
        'print("hello")\n'
    )

    assert (reports / "review.json").exists()
    assert (reports / "changes.diff").exists()
    assert (reports / "validation.json").exists()
    assert archive.exists()

    with zipfile.ZipFile(archive) as zf:
        assert "main.py" in zf.namelist()


def test_clean_project_rejects_nonempty_output(tmp_path):
    source = tmp_path / "input"
    output = tmp_path / "output"

    source.mkdir()
    output.mkdir()

    (source / "main.py").write_text(
        'print("hello")\n',
        encoding="utf-8",
    )

    (output / "existing.txt").write_text(
        "existing",
        encoding="utf-8",
    )

    exit_code = clean_project(source, output)

    assert exit_code == 2
