from pathlib import Path

from codecleaner.review.engine import ReviewEngine


def test_unchanged_file(tmp_path: Path):
    original = tmp_path / "original"
    cleaned = tmp_path / "cleaned"

    original.mkdir()
    cleaned.mkdir()

    (original / "main.py").write_text(
        "print('hello')\n",
        encoding="utf-8",
    )
    (cleaned / "main.py").write_text(
        "print('hello')\n",
        encoding="utf-8",
    )

    result = ReviewEngine().compare_file(
        original,
        cleaned,
        Path("main.py"),
    )

    assert result.status == "unchanged"
    assert result.additions == 0
    assert result.deletions == 0
    assert result.diff == ""


def test_changed_file_diff(tmp_path: Path):
    original = tmp_path / "original"
    cleaned = tmp_path / "cleaned"

    original.mkdir()
    cleaned.mkdir()

    (original / "main.py").write_text(
        "# Generated by ChatGPT\nprint('hello')\n",
        encoding="utf-8",
    )
    (cleaned / "main.py").write_text(
        "print('hello')\n",
        encoding="utf-8",
    )

    result = ReviewEngine().compare_file(
        original,
        cleaned,
        Path("main.py"),
    )

    assert result.status == "changed"
    assert result.deletions == 1
    assert result.additions == 0
    assert "Generated by ChatGPT" in result.diff


def test_build_report(tmp_path: Path):
    original = tmp_path / "original"
    cleaned = tmp_path / "cleaned"

    original.mkdir()
    cleaned.mkdir()

    (original / "main.py").write_text(
        "# AI generated\nprint('hello')\n",
        encoding="utf-8",
    )
    (cleaned / "main.py").write_text(
        "print('hello')\n",
        encoding="utf-8",
    )

    report = ReviewEngine().build_report(
        original,
        cleaned,
        [Path("main.py")],
        findings=1,
    )

    assert report.findings == 1
    assert report.changed_files == 1
    assert report.deletions == 1
    assert report.additions == 0
    assert report.has_changes


def test_new_file_is_reported(tmp_path: Path):
    original = tmp_path / "original"
    cleaned = tmp_path / "cleaned"

    original.mkdir()
    cleaned.mkdir()

    (cleaned / "new.py").write_text(
        "print('new')\n",
        encoding="utf-8",
    )

    report = ReviewEngine().build_report(
        original,
        cleaned,
        [],
    )

    assert report.changed_files == 1
    assert report.additions == 1


def test_removed_file_is_reported(tmp_path: Path):
    original = tmp_path / "original"
    cleaned = tmp_path / "cleaned"

    original.mkdir()
    cleaned.mkdir()

    (original / "old.py").write_text(
        "print('old')\n",
        encoding="utf-8",
    )

    report = ReviewEngine().build_report(
        original,
        cleaned,
        [],
    )

    assert report.changed_files == 1
    assert report.deletions == 1
