from codecleaner.classification.engine import ClassificationEngine
from codecleaner.classification.models import Decision, Severity
from codecleaner.detection.models import (
    DetectionFinding,
    FindingAction,
    FindingType,
)


def make_finding(
    confidence=0.99,
    action=FindingAction.REMOVE,
    category=FindingType.AI_ATTRIBUTION,
):
    return DetectionFinding(
        finding_id="abc123",
        rule_id="ATTR-001",
        file="main.py",
        line=1,
        finding_type=category,
        action=action,
        confidence=confidence,
        matched_text="# Generated by Claude",
        reason="Explicit AI attribution.",
    )


def test_high_confidence_remove():
    result = ClassificationEngine().classify(
        make_finding(confidence=0.99)
    )

    assert result.decision == Decision.REMOVE
    assert result.severity == Severity.LOW


def test_medium_confidence_requires_review():
    result = ClassificationEngine().classify(
        make_finding(confidence=0.90)
    )

    assert result.decision == Decision.REVIEW
    assert result.severity == Severity.MEDIUM


def test_review_action_stays_review():
    result = ClassificationEngine().classify(
        make_finding(
            confidence=0.90,
            action=FindingAction.REVIEW,
            category=FindingType.AI_ASSISTANT_MARKER,
        )
    )

    assert result.decision == Decision.REVIEW


def test_summary_counts():
    engine = ClassificationEngine()

    findings = engine.classify_many([
        make_finding(confidence=0.99),
        make_finding(confidence=0.99),
        make_finding(confidence=0.90),
    ])

    summary = engine.summarize(findings)

    assert summary.total == 3
    assert summary.remove == 2
    assert summary.review == 1
    assert summary.keep == 0
    assert summary.low == 2
    assert summary.medium == 1


def test_serialization():
    result = ClassificationEngine().classify(
        make_finding()
    )

    data = result.to_dict()

    assert data["decision"] == "remove"
    assert data["severity"] == "low"
    assert data["confidence"] == 0.99
