from pathlib import Path

from codecleaner.detection.engine import DetectionEngine
from codecleaner.detection.models import FindingAction, FindingType


def test_detects_claude_attribution(tmp_path: Path):
    path = tmp_path / "main.py"
    path.write_text(
        "# Generated by Claude\n"
        "def hello():\n"
        "    return 'hello'\n",
        encoding="utf-8",
    )

    findings = DetectionEngine().scan_file(tmp_path, path)

    assert len(findings) == 1
    assert findings[0].finding_type == FindingType.AI_ATTRIBUTION
    assert findings[0].action == FindingAction.REMOVE
    assert findings[0].confidence == 0.99


def test_detects_chatgpt_attribution(tmp_path: Path):
    path = tmp_path / "main.js"
    path.write_text(
        "// Created with ChatGPT\n"
        "function hello() { return 'hello'; }\n",
        encoding="utf-8",
    )

    findings = DetectionEngine().scan_file(tmp_path, path)

    assert len(findings) == 1


def test_preserves_license(tmp_path: Path):
    path = tmp_path / "main.py"
    path.write_text(
        "# Copyright 2026 Example\n"
        "# Licensed under the MIT License\n"
        "print('hello')\n",
        encoding="utf-8",
    )

    findings = DetectionEngine().scan_file(tmp_path, path)

    assert findings == []


def test_review_rule_is_not_auto_remove(tmp_path: Path):
    path = tmp_path / "main.py"
    path.write_text(
        "# AI Assistant: generated helper\n",
        encoding="utf-8",
    )

    findings = DetectionEngine().scan_file(tmp_path, path)

    assert len(findings) == 1
    assert findings[0].action == FindingAction.REVIEW
    assert findings[0].confidence == 0.90


def test_finding_id_is_stable(tmp_path: Path):
    path = tmp_path / "main.py"
    path.write_text(
        "# Generated by Claude\n",
        encoding="utf-8",
    )

    engine = DetectionEngine()

    first = engine.scan_file(tmp_path, path)
    second = engine.scan_file(tmp_path, path)

    assert first[0].finding_id == second[0].finding_id
