from __future__ import annotations

from collections import Counter
from pathlib import Path
import re

from codecleaner.detection.protection import protect_line
from .models import FileFeatures


BOILERPLATE_RE = re.compile(
    r"(?:here'?s|below is|this function|this class|"
    r"this code|generated|implementation|example usage|"
    r"feel free to|you can|note that)",
    re.IGNORECASE,
)

GENERATED_RE = re.compile(
    r"(?:generated by|created by|written by|"
    r"chatgpt|claude|cursor|copilot|gemini|codeium|"
    r"ai[- ]generated|language model|llm)",
    re.IGNORECASE,
)

COMMENT_RE = re.compile(r"^s*(?:#|//|/*+|*|<!--|--)")


class FeatureExtractor:
    """Deterministically extract code-noise signals without changing source."""

    def extract_file(self, root: Path, path: Path) -> FileFeatures:
        root = Path(root)
        path = Path(path)

        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            return self._empty_features(root, path)

        lines = text.splitlines()
        total = len(lines)
        blank = sum(1 for line in lines if not line.strip())
        comments = []
        code_values = []
        boilerplate = 0
        generated = 0

        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue

            is_comment = COMMENT_RE.match(line) is not None
            if is_comment or protect_line(line).protected:
                normalized = re.sub(r"s+", " ", stripped).lower()
                comments.append(normalized)
                if BOILERPLATE_RE.search(stripped):
                    boilerplate += 1
                if GENERATED_RE.search(stripped):
                    generated += 1
                continue

            code_values.append(re.sub(r"s+", " ", stripped))

        comment_count = len(comments)
        code_count = len(code_values)

        repeated = max(0, comment_count - len(set(comments)))
        comment_repetition = repeated / comment_count if comment_count else 0.0

        code_counter = Counter(code_values)
        duplicate_code = sum(
            count - 1 for count in code_counter.values() if count > 1
        )
        duplicate_line_ratio = duplicate_code / code_count if code_count else 0.0

        denominator = total or 1
        return FileFeatures(
            file=str(path.relative_to(root)),
            total_lines=total,
            code_lines=code_count,
            comment_lines=comment_count,
            blank_lines=blank,
            comment_ratio=comment_count / denominator,
            blank_line_ratio=blank / denominator,
            comment_repetition=comment_repetition,
            duplicate_line_ratio=duplicate_line_ratio,
            duplicate_block_signal=self._duplicate_block_signal(lines),
            boilerplate_density=boilerplate / denominator,
            generated_phrase_density=generated / denominator,
            code_density=code_count / denominator,
        )

    def extract_project(
        self,
        root: Path,
        files: list[Path],
    ) -> tuple[FileFeatures, ...]:
        return tuple(self.extract_file(root, path) for path in files)

    @staticmethod
    def _empty_features(root: Path, path: Path) -> FileFeatures:
        return FileFeatures(
            file=str(path.relative_to(root)),
            total_lines=0,
            code_lines=0,
            comment_lines=0,
            blank_lines=0,
            comment_ratio=0.0,
            blank_line_ratio=0.0,
            comment_repetition=0.0,
            duplicate_line_ratio=0.0,
            duplicate_block_signal=0.0,
            boilerplate_density=0.0,
            generated_phrase_density=0.0,
            code_density=0.0,
        )

    @staticmethod
    def _duplicate_block_signal(lines: list[str]) -> float:
        normalized = [
            re.sub(r"s+", " ", line.strip())
            for line in lines
            if line.strip()
        ]
        if len(normalized) < 4:
            return 0.0

        blocks = Counter(
            tuple(normalized[index:index + 3])
            for index in range(len(normalized) - 2)
        )
        repeated = sum(1 for count in blocks.values() if count > 1)
        return repeated / max(1, len(blocks))
