from __future__ import annotations

from collections import Counter
from pathlib import Path
import re

from codecleaner.detection.protection import protect_line
from .models import FileFeatures


BOILERPLATE_RE = re.compile(
    r"\b(?:here'?s|below is|this function|this class|"
    r"this code|generated|implementation|example usage|"
    r"feel free to|you can|note that)\b",
    re.IGNORECASE,
)

GENERATED_RE = re.compile(
    r"\b(?:generated by|created by|written by|"
    r"chatgpt|claude|cursor|copilot|gemini|codeium|"
    r"ai[- ]generated|language model|llm)\b",
    re.IGNORECASE,
)

COMMENT_RE = re.compile(r"^\s*(?:#|//|/\*+|\*|<!--|--)")


class FeatureExtractor:
    """Deterministically extract code-noise signals without changing source."""

    def extract_file(self, root: Path, path: Path) -> FileFeatures:
        root = Path(root)
        path = Path(path)

        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            return FileFeatures(
                file=str(path.relative_to(root)),
                total_lines=0,
                code_lines=0,
                comment_lines=0,
                blank_lines=0,
                comment_ratio=0.0,
                blank_line_ratio=0.0,
                comment_repetition=0.0,
                duplicate_line_ratio=0.0,
                duplicate_block_signal=0.0,
                boilerplate_density=0.0,
                generated_phrase_density=0.0,
                code_density=0.0,
            )

        lines = text.splitlines()
        total = len(lines)
        blank = 0
        comments = []
        code = 0
        boilerplate = 0
        generated = 0

        for line in lines:
            stripped = line.strip()
            if not stripped:
                blank += 1
                continue

            if COMMENT_RE.match(line) or protect_line(line).protected:
                comments.append(re.sub(r"\s+", " ", stripped).lower())
                if BOILERPLATE_RE.search(stripped):
                    boilerplate += 1
                if GENERATED_RE.search(stripped):
                    generated += 1
                continue

            code += 1

        comment_count = len(comments)
        repeated = comment_count - len(set(comments))
        duplicate_comments = max(0, repeated)
        comment_repetition = (
            duplicate_comments / comment_count if comment_count else 0.0
        )

        code_values = [
            re.sub(r"\s+", " ", line.strip())
            for line in lines
            if line.strip() and not COMMENT_RE.match(line)
        ]
        code_counter = Counter(code_values)
        duplicate_code = sum(
            count - 1
            for count in code_counter.values()
            if count > 1
        )
        duplicate_line_ratio = duplicate_code / len(code_values) if code_values else 0.0

        duplicate_block_signal = self._duplicate_block_signal(lines)

        denominator = total or 1
        return FileFeatures(
            file=str(path.relative_to(root)),
            total_lines=total,
            code_lines=code,
            comment_lines=comment_count,
            blank_lines=blank,
            comment_ratio=comment_count / denominator,
            blank_line_ratio=blank / denominator,
            comment_repetition=comment_repetition,
            duplicate_line_ratio=duplicate_line_ratio,
            duplicate_block_signal=duplicate_block_signal,
            boilerplate_density=boilerplate / denominator,
            generated_phrase_density=generated / denominator,
            code_density=code / denominator,
        )

    def extract_project(
        self,
        root: Path,
        files: list[Path],
    ) -> tuple[FileFeatures, ...]:
        return tuple(self.extract_file(root, path) for path in files)

    @staticmethod
    def _duplicate_block_signal(lines: list[str]) -> float:
        normalized = [
            re.sub(r"\s+", " ", line.strip())
            for line in lines
            if line.strip()
        ]
        if len(normalized) < 4:
            return 0.0

        blocks = Counter(
            tuple(normalized[index:index + 3])
            for index in range(len(normalized) - 2)
        )
        repeated = sum(1 for count in blocks.values() if count > 1)
        return repeated / max(1, len(blocks))
